apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-metrics-example
  namespace: openshift-gitops
spec:
  destination:
    namespace: hackathon
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: /apps/green/nodejs-app/k8s
    repoURL: https://github.com/redhat-scholars/quickstart-workshop/
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true